<?php

use Drupal\Core\Render\Markup;

/**
 * Implements TEMPLATE_preprocess_views_view_field().
 */
function dog_breeds_preprocess_views_view_field(array &$view) {
  $field = $view['field'];

  if ($field->field == 'field_breed_img') {
    $slug = $view['row']->_entity->field_slug->value;
    $imgUrl = \Drupal::service('dog_breeds.breeds_img_service')->getBreedImages($slug);

    if ($imgUrl) {
      $img = "<img src='{$imgUrl}' />";
      $rendered_image = render($img);
      $image_markup = Markup::create($rendered_image);
      $field->last_render = $image_markup;
      $field->last_render_text =$image_markup;
      $view['output'] = $image_markup;
    }
  }
}
