<?php

use Drupal\Core\Block\BlockPluginInterface;

function dog_breed_block_block_view_alter(array &$build, BlockPluginInterface $block) {
  $config = \Drupal::service('config.factory')->get('dog_breed_block.settings');
  $slug = $config->get('dog_breed_slug');
  // This will uppercase the block title.
  $build['#configuration']['label'] = _normalize_title($slug);
}

function _normalize_title($slug) {

  return ucwords(str_replace("-"," ",$slug));

}